### ISSUE TITLE
Optionally suppress the center-annotations in scatter plots

### ISSUE THREAD

**Issue by normanius** [erdogant/pca#47] opened 2023-05-31 16:15 UTC
When creating scatter plots (using [`scatterd`](https://erdogant.github.io/scatterd/pages/html/index.html)), labels are plotted at the center of mass for each point cloud, see below.

Is it possible to optionally suppress those labels? A couple of reasons for this:
- For smaller point clouds and larger number of classes, this can become quite messy. 
- The information is redundant, as the legend also indicates the class category
- The labels can interfere with other content in the plot, see for example the label for the category "versicolor", that interferes with the arrow-annotation "petal length".

<img width="1237" alt="image" src="https://github.com/erdogant/pca/assets/11406002/eb2b6852-7a89-4df7-828c-7ca6b0d9f777">

I noticed around [L656 in pca.py](https://github.com/erdogant/pca/blob/a7b65d6af35abc75f00865bae24b97e23daadb5c/pca/pca.py#L656) that the labels are extracted from the available arguments. But it appears not to be possible to disable the creation of these annotations.

The Rolls-Royce improvement would be, to optionally include those cloud-mass-annotations when placing texts with "adjustText". But again, adding a switch to disable these cloud-annotations would be nice!

**Comment by normanius** [comment] 2023-05-31 18:51
Okay, that's also a possibility. Make it shrink until it's not visible anymore 😆 

Having it in the function API would be maybe a bit cleaner, but for me that's okay so far. Thanks!

**Comment by erdogant** [comment] 2023-08-05 18:47
I am closing this one as the issue is fixed :)

**Closed by erdogant** 2023-08-05 18:47 UTC
